### ISSUE TITLE
input_data.py 的链接失效 

### ISSUE THREAD

**Issue by volvet** [jikexueyuanwiki/tensorflow-zh#108]
https://github.com/jikexueyuanwiki/tensorflow-zh/blob/master/SOURCE/tutorials/mnist_beginners.md
这里，  input_data.py下载的link 为  https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/mnist/input_data.py

但是事实上， 这个link已经失效了，   tensorflow官网上的 MNIST For ML Beginners 这个地方也有同样的问题。   

解决的办法：  input_data.py 依然可以在这里找到 
https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/examples/tutorials/mnist/input_data.py

**Comment by kinderry** [comment]
第二个也失效了

**Comment by liuenliang** [comment]
可用，顶
