### ISSUE TITLE
TensorFlow 官方文档中文版中目录与各章标题不符

### ISSUE THREAD

**Issue by JinhaiZ** [jikexueyuanwiki/tensorflow-zh#134]
在[TensorFlow 官方文档中文版](http://wiki.jikexueyuan.com/project/tensorflow-zh/)网页版的导航目录与各章标题不符。例如导航栏目录中的介绍，打开后该章节内容为[简介](http://wiki.jikexueyuan.com/project/tensorflow-zh/get_started/introduction.html); 还比如导航栏目录中的递归神经网络，打开后该章节内容为[循环神经网络](http://wiki.jikexueyuan.com/project/tensorflow-zh/tutorials/recurrent.html)。wiki百科上将[recurrent neural network](https://zh.wikipedia.org/zh-cn/%E9%80%92%E5%BD%92%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C)翻译为（时间）递归神经网络，而recursive neural network翻译为（结构）递归神经网络，以表示recursive neural network是recurrent neural network的一个分支。个人认为两种神经网络还是不要混淆为好。

**Comment by wenquan0hf** [comment]
已采纳，很不错的建议，确实如此，Thanks
![image](https://cloud.githubusercontent.com/assets/11265808/13874864/740f8e84-ed35-11e5-8585-65d7870a2722.png)
