### ISSUE TITLE
官方文档中的很多学习教程的超链接在文档中点击没反应，学习资料找起来很费劲啊！

### ISSUE THREAD

**Issue by ForeverDreamer** [jikexueyuanwiki/tensorflow-zh#140]
![qq 20160309103005](https://cloud.githubusercontent.com/assets/5547460/13623573/88d52a04-e5e2-11e5-8195-068c02df54e7.png)
![qq 20160309103245](https://cloud.githubusercontent.com/assets/5547460/13623572/88d44698-e5e2-11e5-8b7a-3cc7ce746019.png)

**Comment by wenquan0hf** [comment]
@ForeverDreamer  问题已经解决，欢迎提交PR，最近事情比较多，没能及时改正，现在收集了大家的意见，对这个版本做了维护。
