### ISSUE TITLE
文档版本不同步

### ISSUE THREAD

**Issue by jas0n1ee** [jikexueyuanwiki/tensorflow-zh#142]
e.g.
[此处, 中文文档中为](https://github.com/jikexueyuanwiki/tensorflow-zh/blob/master/SOURCE/tutorials/mnist_beginners.md#mnist数据集)
```python
import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
```
[Google 的r0.6.0/r0.7/master文档中为](https://www.tensorflow.org/versions/0.6.0/tutorials/mnist/beginners/index.html#the-mnist-data)
```python
import tensorflow.examples.tutorials.mnist.input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
```

**Comment by jas0n1ee** [comment]
[In zh version](https://github.com/jikexueyuanwiki/tensorflow-zh/blob/master/SOURCE/tutorials/mnist_beginners.md#实现回归模型)
```python
x = tf.placeholder("float", [None, 784])
```

[In Google version](https://www.tensorflow.org/versions/r0.7/tutorials/mnist/beginners/index.html#implementing-the-regression)
```python
x = tf.placeholder(tf.float32, [None, 784])
```

**Comment by qiaohaijun** [comment]
可以提一个PR

**Comment by qiaohaijun** [comment]
已修改
