### ISSUE TITLE
文档笔误（官网已修正，翻译文档依旧）

### ISSUE THREAD

**Issue by yatsuki** [jikexueyuanwiki/tensorflow-zh#143]
笔误位置：/tutorials/mnist/beginners/The MNIST Data
`For example, 0 would be ([1,0,0,0,0,0,0,0,0,0,0])`
文档原意应该是指其数组为10维数组，但是给出的例子却是一个11维数组。
官网修正文本如下：
`For example, 3 would be ([0,0,0,1,0,0,0,0,0,0])`

**Comment by qiaohaijun** [comment]
可以提一个PR

**Comment by qiaohaijun** [comment]
可否给出文件的link
