### ISSUE TITLE
递归还是循环？

### ISSUE THREAD

**Issue by HaloWang** [jikexueyuanwiki/tensorflow-zh#158]
[这里](http://wiki.jikexueyuan.com/project/tensorflow-zh/tutorials/recurrent.html) 所介绍的 RNN 是递归神经网络还是循环神经网络呢？应该是循环神经网络吧？
发现有类似的 [issue-#134](https://github.com/jikexueyuanwiki/tensorflow-zh/issues/134) 了

**Comment by terry182** [comment]
看英文文檔是Recurrent 的RNN

**Comment by OverrideSkywalker** [comment]
纠结这个中文译名干嘛呢？循环或者递归，知道意思就行啦

**Comment by snailcoder** [comment]
循环神经网络。递归神经网络是Recursive Neural Network
