### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by iphyer** [jikexueyuanwiki/tensorflow-zh#24]
参与步骤这个章节的这句话

"翻译过程请参 翻译协作规范 ，完成翻译后提交 pull request 给主仓库的master分支；"
漏掉了一个字吧。

"请参考"或者"请参照"。
然后后面的"翻译协作规范",可以页面内链接过去，一开始还以为在那个文件里面，结果就是下一章节。
或者括号请见下一节。

**Comment by TerenceCooper** [comment]
是的，我也看到了。最好可以按楼主的建议改。

**Comment by floydzhang315** [comment]
已按照楼主建议修改，多谢！

**Comment by iphyer** [comment]
OK!已经改好！那我close这个了。
