### ISSUE TITLE
专业术语如果能早点出来，大家翻译的时候会比较统一，文档整体会比较连贯。

### ISSUE THREAD

**Issue by TerenceCooper** [jikexueyuanwiki/tensorflow-zh#28]
如果是 glossary 部分能早点出来的话，翻的过程中感觉会比较轻松。这部分当中的很多术语，几乎每一其他部分都会用到。如果大家翻译时能统一，这对于减少歧义，加快翻译速度应该都有好处，大家觉得怎么样？

**Comment by wenquan0hf** [comment]
good.

**Comment by floydzhang315** [comment]
同意，有人正在翻译，翻好后一起校对，大家统一一下

**Comment by qiaohaijun** [comment]
单独做一个术语对照表
