### ISSUE TITLE
对遇到的一些词汇的翻译建议

### ISSUE THREAD

**Issue by wangaicc** [jikexueyuanwiki/tensorflow-zh#55]
建议 翻译中 遇到的 TensorBoard 用格式  \*\*\*TensorBoard\*\*\*      ***TensorBoard*** （斜体加粗）来凸显！
而对于一些专业词汇，如：Python  用格式  \*\*\*Python\*\*\*   **Python** (加粗)来凸显

**Comment by TerenceCooper** [comment]
这个工作是不是可以由校对的人来完成会比较好？
